apiVersion: v1
kind: PersistentVolume
metadata:
  name: anomaly-detector-pv
  namespace: dd-flow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/dd-flow/anomaly-detector-model"  
