apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anomaly-detector-pvc
  namespace: dd-flow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
