apiVersion: apps/v1
kind: Deployment
metadata:
  name: goflow2
  namespace: dd-net
  labels:
    app: goflow2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goflow2
  template:
    metadata:
      labels:
        app: goflow2
      annotations:
        ad.datadoghq.com/goflow2.logs: '[{"source": "goflow2", "service": "goflow2"}]'
    spec:
      containers:
        - name: goflow2
          image: netsampler/goflow2:latest
          args:
            - "-loglevel=info" 
            - "-transport=kafka"
            - "-transport.kafka.brokers=kafka-service.kafka.svc.cluster.local:9092"
            - "-transport.kafka.topic=flows"
            - "-format=json"
          ports:
            - containerPort: 2055
              protocol: UDP
            - containerPort: 8080
              protocol: TCP
