apiVersion: apps/v1
kind: Deployment
metadata:
  name: goflow2
  namespace: dd-net
  labels:
    app: goflow2
spec:
  replicas: 1
  dnsPolicy: ClusterFirst
  selector:
    matchLabels:
      app: goflow2
  template:
    metadata:
      labels:
        app: goflow2
    spec:
      containers:
        - name: goflow2
          image: netsampler/goflow2:latest
          args:
            - "-transport=kafka"
            - "-transport.kafka.brokers=kafka-service.kafka.svc.cluster.local:9092"
            - "-transport.kafka.topic=flows"
            - "-format=bin"
          ports:
            - containerPort: 2055
              protocol: UDP
