apiVersion: apps/v1
kind: Deployment
metadata:
  name: goflow2
  namespace: dd-net
  labels:
    app: goflow2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goflow2
  template:
    metadata:
      labels:
        app: goflow2
    spec:
      containers:
      - name: goflow2
        image: netsampler/goflow2:latest
        args:
        - "-listen=ipfix://:2055"
        - "-transport=file"
        - "-transport.file="
        - "-format=json"
        ports:
        - containerPort: 2055
          protocol: UDP