apiVersion: v1
kind: Service
metadata:
  name: goflow2
  namespace: dd-net
spec:
  selector:
    app: goflow2
  type: LoadBalancer
  ports:
    - name: netflow
      protocol: UDP
      port: 2055
      targetPort: 2055
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
