apiVersion: v1
kind: Service
metadata:
  name: goflow2
  namespace: dd-net
  labels:
    app: goflow2
spec:
  type: LoadBalancer 
  ports:
  - port: 2055
    protocol: UDP
    targetPort: 2055
  selector:
    app: goflow2