apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: dd-flow
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
      annotations:
        ad.datadoghq.com/processor.logs: '[{"source": "python", "service": "processor"}]'
    spec:
      containers:
        - name: processor
          image: laols/dd-flow-processor:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: dd-flow
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
