apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: dd-flow
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 8080 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/processor" }
                              route:
                                cluster: dd-flow-processor
                                retry_policy:
                                  retry_on: "5xx"
                                  num_retries: 3
                                  per_try_timeout: 2s
                            - match: { prefix: "/anomaly" }
                              route:
                                cluster: dd-flow-anomaly-detector
                                retry_policy:
                                  retry_on: "5xx"
                                  num_retries: 3
                                  per_try_timeout: 2s
                            - match: { prefix: "/aggregator" }
                              route:
                                cluster: dd-flow-aggregator
                                retry_policy:
                                  retry_on: "5xx"
                                  num_retries: 3
                                  per_try_timeout: 2s
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: dd-flow-processor
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: dd-flow-processor
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: dd-flow-processor.dd-flow.svc.cluster.local, port_value: 5000 }
          health_checks:
            - timeout: 5s
              interval: 10s
              unhealthy_threshold: 3
              healthy_threshold: 3
              tcp_health_check: {}

        - name: dd-flow-anomaly-detector
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: dd-flow-anomaly-detector
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: dd-flow-anomaly-detector.dd-flow.svc.cluster.local, port_value: 5001 }
          health_checks:
            - timeout: 5s
              interval: 10s
              unhealthy_threshold: 3
              healthy_threshold: 3
              tcp_health_check: {}

        - name: dd-flow-aggregator
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: dd-flow-aggregator
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: dd-flow-aggregator.dd-flow.svc.cluster.local, port_value: 5002 }
          health_checks:
            - timeout: 5s
              interval: 10s
              unhealthy_threshold: 3
              healthy_threshold: 3
              tcp_health_check: {}

    admin:
      access_log_path: "/dev/null"
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
