apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: dd-flow
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 8080 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/processor" }
                              route: { cluster: processor }
                            - match: { prefix: "/anomaly" }
                              route: { cluster: anomaly-detector }
                            - match: { prefix: "/aggregator" }
                              route: { cluster: aggregator }
                    http_filters:
                      - name: envoy.filters.http.router

      clusters:
        - name: processor
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: processor
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: processor.dd-flow.svc.cluster.local, port_value: 5000 }

        - name: anomaly-detector
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: anomaly-detector
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: anomaly-detector.dd-flow.svc.cluster.local, port_value: 5001 }

        - name: aggregator
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: aggregator
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address: { address: aggregator.dd-flow.svc.cluster.local, port_value: 5002 }
