apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dd-flow
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
  type: LoadBalancer
