name: Build and Deploy Anomaly Detector

on:
  push:
    branches:
      - main
    paths:
      - 'anomaly-detector/**'
      - 'manifests/deployment.yaml'
      - '.github/workflows/build-deploy-anomaly-detector.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set commit SHA for version
      id: set_commit_sha
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        REPO_URL=$(git config --get remote.origin.url)
        COMMIT_SHA=$(git rev-parse HEAD)

        docker build -f anomaly-detector/Dockerfile anomaly-detector/ \
          -t laols/dd-flow-anomaly-detector:latest \
          --build-arg DD_GIT_REPOSITORY_URL="$REPO_URL" \
          --build-arg DD_GIT_COMMIT_SHA="$COMMIT_SHA" \
          --build-arg DD_VERSION=${{ env.VERSION }}

    - name: Push Docker image
      run: |
        docker push laols/dd-flow-anomaly-detector:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    timeout-minutes: 5

    env:
      DD_BETA_COMMANDS_ENABLED: 1
      DD_GITHUB_JOB_NAME: Deploy to Kubernetes
      DD_SITE: datadoghq.eu
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

    - name: Deploy Anomaly Detector to Kubernetes
      run: |
        kubectl apply -f anomaly-detector/manifests/deployment.yaml --insecure-skip-tls-verify
        kubectl apply -f anomaly-detector/manifests/pv.yaml --insecure-skip-tls-verify
        kubectl apply -f anomaly-detector/manifests/pvc.yaml --insecure-skip-tls-verify
        
    - name: Mark deployment in Datadog
      run: |
        npx @datadog/datadog-ci deployment mark --env production --service anomaly-detector --revision "${{ github.sha }}"

    - name: Track deployment in Datadog
      env:
        DD_BETA_COMMANDS_ENABLED: 1
        DD_SITE: 'datadoghq.eu'
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      run: |
        npx @datadog/datadog-ci dora deployment --service anomaly-detector --env production --started-at $(date +%s) --git-repository-url "${{ github.event.repository.html_url }}" --git-commit-sha ${{ github.sha }}
