name: Deploy goflow2
on:
  push:
    branches:
      - main
    paths:
      - 'goflow2/manifests/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

      - name: Apply goflow2 manifests
        run: |
          kubectl apply -n goflow2 -f goflow2/manifests/deployment.yaml --insecure-skip-tls-verify
          kubectl apply -n goflow2 -f goflow2/manifests/service.yaml --insecure-skip-tls-verify
